Edit pipeline, add coverage, rework structure

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -5,15 +5,14 @@ trigger:
     include:
     - main
     - refs/tags/*
-
+  
 stages:
 
-
-- stage: Code_Checks
-  displayName: pytest unit tests
+- stage: Unit_Tests
+  displayName: Unit Tests
 
   jobs:
-    - job: "pytest"
+    - job: "PyTest"
 
       pool:
         vmImage: ubuntu-20.04
@@ -22,15 +21,16 @@ stages:
         CONDA_ENV: baybe
         CONDA_HOME: /usr/share/miniconda/envs/$(CONDA_ENV)/
         CONDA_ROOT: /usr/share/miniconda/
+        disable.coverage.autogenerate: 'true'
 
       steps:
       - checkout: self
 
       - script: echo "##vso[task.prependpath]$CONDA/bin"
-        displayName: Add conda to PATH
+        displayName: Add Conda to PATH
 
       - task: Cache@2
-        displayName: Use cached conda environment
+        displayName: Use Cached Conda Env
         inputs:
           key: conda | environment.yml
           path: $(CONDA_HOME)
@@ -39,32 +39,64 @@ stages:
       - script: |
           export MAMBA_ROOT_PREFIX=$(CONDA_ROOT)
           curl micro.mamba.pm/install.sh | bash
-        displayName: Install micromamba
+        displayName: Install Micromamba
 
       - script: |
           export MAMBA_ROOT_PREFIX=$(CONDA_ROOT)
           eval "$(micromamba shell hook --shell=bash)"
           micromamba create -y --file environment.yml
-        displayName: Create conda environment (if not restored from cache)
+        displayName: Create Conda Env If Not Cached
         condition: eq(variables.CONDA_CACHE_RESTORED, 'false')
 
       - script: |
           export MAMBA_ROOT_PREFIX=$(CONDA_ROOT)
           eval "$(micromamba shell hook --shell=bash)"
           micromamba activate $(CONDA_ENV)
-          python -m pip install .
-        displayName: "Install BayBE package"
+          python -m pip install '.[extra]'
+        displayName: "Install BayBE Package"
 
       - script: |
           export MAMBA_ROOT_PREFIX=$(CONDA_ROOT)
           eval "$(micromamba shell hook --shell=bash)"
           micromamba activate $(CONDA_ENV)
-          pytest -v -p no:warnings
-        displayName: "Run pytest"
-        workingDirectory: tests
+          python -m pip install unittest-xml-reporting pytest-azurepipelines
+        displayName: Install Code Coverage Requirements"
+
+      - script: |
+          export MAMBA_ROOT_PREFIX=$(CONDA_ROOT)
+          eval "$(micromamba shell hook --shell=bash)"
+          micromamba activate $(CONDA_ENV)
+          cd $(System.DefaultWorkingDirectory)
+          touch ./tests/__init__.py
+          touch ./tests/serialization/__init__.py
+          pytest -v -p no:warnings --cov=baybe --cov-report=xml --junit-xml $(System.DefaultWorkingDirectory)/test-results.xml --cov-report=html ./tests
+        displayName: Run PyTest
+
+      - task: PublishCodeCoverageResults@1
+        displayName: Publish Coverage Report
+        inputs:
+          codeCoverageTool: Cobertura
+          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage.xml
+          reportDirectory: $(System.DefaultWorkingDirectory)/htmlcov
+
+      # Fail if overall coverage is below 70%
+      - script: |
+          export MAMBA_ROOT_PREFIX=$(CONDA_ROOT)
+          eval "$(micromamba shell hook --shell=bash)"
+          micromamba activate $(CONDA_ENV)
+          coverage report --fail-under=70
+        displayName: Assert Overall Coverage
+
+      # Fail if any individual coverage is below 50%
+      - script: |
+          export MAMBA_ROOT_PREFIX=$(CONDA_ROOT)
+          eval "$(micromamba shell hook --shell=bash)"
+          micromamba activate $(CONDA_ENV)
+          coverage report | grep -E -o '[0-9]+%' | tr -d '%' | sed '$d' | awk '{if ($1<50) exit 1 }'  
+        displayName: Assert Individual Coverage
 
 - stage: Lint
-  displayName: Format and lint
+  displayName: Format, Lint, Asserts
 
   jobs:
     - job: "Lint"
@@ -81,10 +113,10 @@ stages:
       - checkout: self
 
       - script: echo "##vso[task.prependpath]$CONDA/bin"
-        displayName: Add conda to PATH
+        displayName: Add Conda to PATH
 
       - task: Cache@2
-        displayName: Use cached conda environment
+        displayName: Use Cached Conda Env
         inputs:
           key: conda | environment.yml
           path: $(CONDA_HOME)
@@ -93,13 +125,13 @@ stages:
       - script: |
           export MAMBA_ROOT_PREFIX=$(CONDA_ROOT)
           curl micro.mamba.pm/install.sh | bash
-        displayName: Install micromamba
+        displayName: Install Micromamba
 
       - script: |
           export MAMBA_ROOT_PREFIX=$(CONDA_ROOT)
           eval "$(micromamba shell hook --shell=bash)"
           micromamba create -y --file environment.yml
-        displayName: Create conda environment (if not restored from cache)
+        displayName: Create Conda Env If Not Cached
         condition: eq(variables.CONDA_CACHE_RESTORED, 'false')
 
       - script: |
@@ -107,24 +139,47 @@ stages:
           eval "$(micromamba shell hook --shell=bash)"
           micromamba activate $(CONDA_ENV)
           ufmt check .
-        displayName: "Run ufmt code formatter"
+        displayName: "Run ufmt Formatter"
 
       - script: |
           export MAMBA_ROOT_PREFIX=$(CONDA_ROOT)
           eval "$(micromamba shell hook --shell=bash)"
           micromamba activate $(CONDA_ENV)
           flake8
-        displayName: "Run flake8 code linter"
+        displayName: "Run flake8 Linter"
 
       - script: |
           export MAMBA_ROOT_PREFIX=$(CONDA_ROOT)
           eval "$(micromamba shell hook --shell=bash)"
           micromamba activate $(CONDA_ENV)
           pylint . --recursive=yes
-        displayName: "Run pylint code linter"
+        displayName: "Run PyLint Linter"
+
+    - job: "Changelog"
+
+      pool:
+        vmImage: ubuntu-20.04
+
+      steps:
+        - script: |
+            CURRENT_COMMIT=`git rev-parse HEAD`
+            #git checkout main
+            git checkout $CURRENT_COMMIT
+            NUM_ADDED=`git diff --numstat origin/main CHANGELOG.md | cut -d$'\t' -f1`
+            echo $NUM_ADDED
+            if [ "$NUM_ADDED" -gt "0" ]; then
+              echo "$NUM_ADDED lines have been added to CHANGELOG.md"
+              exit 0
+            else
+              echo "Nothing has been added to CHANGELOG.md"
+              exit 1
+            fi
+          continueOnError: false
+          displayName: Assert Changelog Edit
 
 - stage: Release  # taken from foundry-local
-  displayName: Push new package version to Azure
+  displayName: Publish package
+  condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
 
   jobs:
     - job: "Release"
@@ -143,23 +198,23 @@ stages:
         - script: |
             pip wheel . --no-deps --wheel-dir dist
             ls -lat dist
-          displayName: 'Run pip wheel .'
+          displayName: 'Create Wheel'
 
         - script: |
             WHL_PATH=$( find dist -name "*.whl")
             echo $WHL_PATH
             echo "##vso[task.setvariable variable=whlName]$WHL_PATH"
-          displayName: 'Get whl filename'
+          displayName: 'Get whl Filename'
 
         - publish: $(System.DefaultWorkingDirectory)/$(whlName)
           artifact: baybe_pipeline_snapshot
-          displayName: 'Upload snapshot artifact'
+          displayName: 'Upload Snapshot Artifact'
 
         # publish on tagged build
         - script: |
             pip install twine
           condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
-          displayName: "Run pip install twine"
+          displayName: "Install Twine"
 
         - task: TwineAuthenticate@1
           inputs:
@@ -174,28 +229,3 @@ stages:
             twine upload -r artifacts --config-file $(PYPIRC_PATH) --verbose $(whlName)
           condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
           displayName: "Twine Upload"
-
-- stage: Changelog
-  displayName: Assert changelog entry exists
-
-  jobs:
-    - job: "Changelog"
-
-      pool:
-        vmImage: ubuntu-20.04
-
-      steps:
-        - script: |
-            CURRENT_COMMIT=`git rev-parse HEAD`
-            git checkout main
-            git checkout $CURRENT_COMMIT
-            NUM_ADDED=`git diff --numstat main CHANGELOG.md | cut -d$'\t' -f1`
-            echo $NUM_ADDED
-            if [ "$NUM_ADDED" -gt "0" ]; then
-              echo "$NUM_ADDED lines have been added to CHANGELOG.md"
-              exit 0
-            else
-              echo "Nothing has been added to CHANGELOG.md"
-              exit 1
-            fi
-          continueOnError: false
